Ui/Areas/admin/Controllers/ArticleController.cs
using DAL.Servieces;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Ui.Tools;

namespace Ui.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "admin")]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly UserManager<AppUser> _userManager;
        public ArticleController(IArticleService articleService, UserManager<AppUser> userManager)
        {
            _articleService = articleService;
            _userManager = userManager;
        }


        // GET: ArticleController
        public ActionResult Index()
        {
            List<Article> model = _articleService.GetAll().ToList();
            return View(model);
        }

        // GET: ArticleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ArticleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article article)
        {
            DateTimePersian dt = new DateTimePersian();
            article.DateTimeCreated = dt.GetDateTimeIR();
            article.UserId = _userManager.GetUserId(User);

            _articleService.Add(article);
            return RedirectToAction("Index");
        }

        // GET: ArticleController/Edit/5
        public ActionResult Edit(int id)
        {
            Article model = _articleService.GetById(id);
            return View(model);
        }

        // POST: ArticleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Article article)
        {
            if (ModelState.IsValid)
            {
                _articleService.Update(article);
                return RedirectToAction("Index");
            }
            else
            {
                return View(article);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Article article = _articleService.GetById(id);
            return View(article);
        }


        // POST: ArticleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection values)
        {
            _articleService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

Ui/Areas/admin/Controllers/OrderController.cs
using DAL.Servieces;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ui.Areas.admin.Models;

namespace Ui.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "admin")]
    public class OrderController : Controller
    {
        private readonly IOrderPaidService _orderPaidService;
        private readonly IUserService _userService;
        private readonly IProductOrderPaidService _productOrderPaidService;
        private readonly IProductService _productService;
        public OrderController(IOrderPaidService orderPaidService, IUserService userService, IProductOrderPaidService productOrderPaidService, IProductService productService)
        {
            _orderPaidService = orderPaidService;
            _userService = userService;
            _productOrderPaidService = productOrderPaidService;
            _productService = productService;
        }
        public IActionResult Index()
        {
            List<OrderPaid> model = _orderPaidService.GetAll().ToList();
            model.ForEach(o => { o.user = _userService.GetById(o.UserId); });
            model.ForEach(o => { o.UserId = string.Join(" ", o.user.FirstName, o.user.LastName); });
            return View(model);
        }

        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
                return View("NotFound");
            ProductOrderPaidViewModel model = new ProductOrderPaidViewModel();
            model.orderPaid = _orderPaidService.GetById((int)id);
            model.productOrderPaids = _productOrderPaidService.GetByOrderPaidId((int)id).ToList();
            model.orderPaid.user = _userService.GetById(model.orderPaid.UserId);
            model.productOrderPaids.ForEach(op => { op.product = _productService.GetById(op.ProductId); });

            return View(model);

            //OrderPaid model = _orderPaidService.GetById(id);

            //OrderPaid tempOrder = _dbcontex.orderPaids.Where(op => op.IdOrderPaid == id).FirstOrDefault();
            //if (tempOrder != null)
            //{
            //    ProductOfOrderPaidViewModel model = new ProductOfOrderPaidViewModel();

            //    //  header of invoice
            //    model.orderPaid = tempOrder;
            //    var user = _dbcontex.Users.Where(u => u.UserName == model.orderPaid.Username).FirstOrDefault();
            //    if (user != null)
            //    {
            //        model.Address = user.Address;
            //        model.Zipcode = user.PostCode;
            //        model.FullName = string.Join(" ", user.FirstName, user.LastName);
            //        model.PhoneNumber = user.PhoneNumber;
            //    }
            //    // get products info
            //    var tempProduct = _dbcontex.productOrderPaid.Where(
            //        po => po.IdOrderPaid == tempOrder.IdOrderPaid).ToList();

            //    foreach (var item in tempProduct)
            //    {
            //        Product p = new Product();
            //        p = _dbcontex.products.Where(p => p.IdProduct == item.IdProduct).FirstOrDefault();
            //        model.ListProductOrderPaid.Add(new Models.ViewModels.ProductOrderPaid
            //        {
            //            IdProduct = item.IdProduct,
            //            Descroption = p.Description,
            //            ImageName = p.ImageName,
            //            NameProduct = p.NameProduct,
            //            Price = item.Price,
            //            QuantityProduct = item.QuantityProduct
            //        });
            //    }
            //    return View(model);
            //}
            //else
            //{
            //    return NotFound();
            //}

        }
    }
}

Ui/Controllers/ProductController.cs
using DAL.Servieces;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Graph;
using Ui.Models;
using Ui.Tools;

namespace Ui.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IArchiveService _archiveService;
        private readonly ICommentService _commentService;
        private readonly IFeatureService _featureService;
        private readonly IUserService _userService;
        private readonly SettingXML _setting;
        private readonly UserManager<AppUser> _userManager;


        public ProductController(IProductService productService, ICategoryService categoryService, IArchiveService archiveService, ICommentService commentService, IFeatureService featureService, UserManager<AppUser> userManager, IUserService userService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _archiveService = archiveService;
            _commentService = commentService;
            _featureService = featureService;
            _userManager = userManager;
            _userService = userService;

            _setting = new SettingXML();
        }

        public IActionResult ShowDetails(int Id)
        {
            if (Id == 0)
                return RedirectToAction(actionName: "Index", controllerName: "Home");

            ProductViewModel model = new ProductViewModel();
            model.Product = _productService.GetById(Id);
            model.Categories = _categoryService.GetAll().ToList();
            model.Archives = _archiveService.GetByProductId(Id).ToList();
            model.Comments = _commentService.GetByProductId(Id).ToList();
            model.Features = _featureService.GetByProductId(Id);
            model.SameProducts = _productService.GetSameProducts(model.Product.CategoryId).ToList();
            string userId = _userManager.GetUserId(User);
            ViewBag.HasWrittenComment = _commentService.HasWrittenComment(userId, Id); // sign in + has no any comment

            return View(model);
        }

        public IActionResult ShowCategories(int Id)
        {
            CategoryOfProductViewModel model = new CategoryOfProductViewModel();
            model.Categories = _categoryService.GetAll().ToList();
            model.Products = _productService.GetByCategory(Id).ToList();
            model.CategoryName = _categoryService.GetById(Id).Name;
            model.ImageName = _categoryService.GetById(Id).FileName;

            return View(model);
        }

        public IActionResult ShowCart()
        {

            ProductCartViewModel model = new ProductCartViewModel();
            model.Categories = _categoryService.GetAll().ToList();
            if (Request.Cookies["_product"] != null)
            {
                // Ids :::    2,3,4,5,
                string cookeisProductId = Request.Cookies["_product"].ToString();
                if (cookeisProductId != null && cookeisProductId != string.Empty)
                {
                    cookeisProductId = cookeisProductId.Substring(0, cookeisProductId.Length - 1);
                    model.Products = _productService.GetByListProductId(cookeisProductId).ToList();
                }
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult AddToCart(int id)
        {
            var product = _productService.GetById(id);
            if (product != null)
            {
                // check exist cookies
                if (Request.Cookies["_product"] == null)
                {
                    Response.Cookies.Append("_product", id + ",", new CookieOptions()
                    {
                        Expires = DateTime.Now.AddMinutes(_setting.TimeExpiresForCookeis)
                    });
                    return Json(new { statue = "success", message = "در لیست افزوده شد", basket_count = 1 });
                }
                else
                {
                    string cookiecontent = Request.Cookies["_product"].ToString();
                    // exist in list
                    if (cookiecontent.Contains(id + ",") == true)
                    {
                        int countItem = cookiecontent.Split(",").Where(c => c != "").Count();
                        return Json(new { statue = "exist", message = "این محصول در لیست شما وجود دارد", basket_count = countItem });
                    }
                    else
                    {
                        // not exist in list
                        cookiecontent += id + ",";
                        Response.Cookies.Append("_product", cookiecontent, new CookieOptions()
                        {
                            Expires = DateTime.Now.AddMinutes(_setting.TimeExpiresForCookeis)
                        });
                        int count_item = cookiecontent.Split(",").Where(r => r != "").Count();
                        string[] list_id = cookiecontent.Split(",").Where(r => r != "").ToArray();
                        return Json(new { statue = "success", message = "در لیست افزوده شد", basket_count = count_item });
                    }


                }
            }
            else
            {
                return Json(new { status = "fail", message = "این محصول یافت نشد" });
            }

        }

        [HttpGet]
        public IActionResult DeleteFromCart(int? id)
        {
            // send count product to cart
            if (Request.Cookies["_product"] != null)
            {
                string cookiecontent = Request.Cookies["_product"].ToString();
                List<string> listId = cookiecontent.Split(",").Where(c => c != "").ToList();
                // remove currnet list id
                listId.Remove(id.ToString());
                // clear coockies _product
                Response.Cookies.Delete("_product");
                if (listId.Count == 0)
                {
                    return RedirectToAction("ShowCart");
                }
                string cookeisProductId = "";
                // try to add other id
                foreach (var IdProduct in listId)
                {
                    cookeisProductId += cookeisProductId + IdProduct + ",";
                }
                if (cookeisProductId != null && cookeisProductId != string.Empty)
                {
                    Response.Cookies.Append("_product", cookeisProductId, new Microsoft.AspNetCore.Http.CookieOptions()
                    {
                        Expires = DateTime.Now.AddMinutes(45)
                    });
                }

                return RedirectToAction("ShowCart");
            }
            else
            { ViewBag.countItem = 0; }

            return RedirectToAction("ShowCart");
        }

        public IActionResult ShowInvoice()
        {
            InvoiceViewModel model = new InvoiceViewModel();
            model.Categories = _categoryService.GetAll().ToList();

            string userId = _userManager.GetUserId(User);
            model.UserInfo = _userService.GetById(userId);
            model.CompanyInfo = new AppUser
            {
                FirstName = _setting.Name,
                Address = _setting.Address,
                Zipcode = _setting.Zipcode,
                PhoneNumber = _setting.Phone
            };

            if (Request.Cookies["_product"] != null)
            {
                // Ids :::    2,3,4,5,
                string cookeisProductId = Request.Cookies["_product"].ToString();
                if (cookeisProductId != null && cookeisProductId != string.Empty)
                {
                    cookeisProductId = cookeisProductId.Substring(0, cookeisProductId.Length - 1);
                    model.Products = _productService.GetByListProductId(cookeisProductId).ToList();
                }
            }
            DateTimePersian dt = new DateTimePersian();
            model.DateTimeCreateIR = dt.GetDateIR();

            return View(model);
        }

        #region comment
        //[Authorize(Roles = "user")]
        [Authorize(Roles = "admin,user")]
        public IActionResult saveComment(int id, string TextComment)
        {
            try
            {

                if (id == null || id == 0)
                    return RedirectToAction(actionName: "Index", controllerName: "Home");
                Comment model = new Comment();
                DateTimePersian dt = new DateTimePersian();
                string userId = _userManager.GetUserId(User);
                AppUser user = _userService.GetById(userId);
                model.FullName = user.FirstName + " " + user.LastName;
                model.UserId = _userManager.GetUserId(User);
                model.ProductId = id;
                model.TextComment = TextComment;
                model.TimeStampIR = dt.GetDateTimeIR();
                _commentService.Add(model);

                return RedirectToAction(actionName: "ShowDetails", new {Id = model.ProductId});
            }
            catch
            {
                return RedirectToAction(actionName: "Index", controllerName: "Home");
            }
        }


        #endregion



    }
}

Ui/Views/Shared/_CommentAdmin.cshtml
@model Entities.Comment


<div class="div-cart col-12 shadow-sm">
    <form id="formComment" asp-controller="Comment" asp-action="SetReply" asp-area="admin" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <h6>
                @Model.FullName
                @if (Model.IsChecked == true)
                {
                    <span class="text-success"> -- تایید شده </span>
                }
            </h6>

            <br />
            <p>@Model.TextComment <span class="badge-light"> @Model.TimeStampIR </span></p>
        </div>

        <div class="form-group">
            <textarea placeholder="نوشتن پاسخ" class="form-control form-control-sm text-info" asp-for="ReplyComment" rows="2"
                      style="border-width: 0px 1px 0px 0px;">@if (Model.ReplyComment != string.Empty)
                {
                    @Model.ReplyComment
                }</textarea>
        </div>


        <input type="hidden" asp-for="Id" />

        @if (Model.IsChecked == true)
        {
            <button type="submit" class="btn btn-success btn-sm pr-3 pl-3">ثبت پاسخ</button>
        }
        else
        {
            <button type="submit" class="btn btn-primary btn-sm pr-3 pl-3">تایید و نمایش</button>
        }

        @*<a asp-controller="Comment" asp-action="Decline" asp-area="admin" asp-route-id="@comment.IdComment"
        class="btn btn-sm btn-outline-warning pr-5 pl-5">رد</a>*@
        <a asp-controller="Comment" asp-action="Remove" asp-route-id="@Model.Id" asp-area="admin"
           class="btn btn-sm btn-outline-danger pr-3 pl-3 ml-3 mr-3">حذف</a>
        <a target="_blank" asp-controller="Product" asp-area="" asp-action="ShowDetails"
           asp-route-id="@Model.ProductId"
           class="text-primary mr-3 ml-3">مشاهده محصول</a>
    </form>
</div>

Ui/Views/Shared/_ContactUs.cshtml
@{
    SettingXML info = new SettingXML();

    <div class="container-fluid" style="margin-bottom:45px;">

        <div class="container">
            <h3>
                راه ارتباطی با فروشگاه
                <span> <a class="btn btn-dark btn-sm" asp-action="Articles" asp-controller="Article" asp-area="">مقالات</a></span>

            </h3>

            <div class="row div-cart shadow">
                <div class="container div-cart">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="news-form">
                                <h5>اصالت فروشگاه</h5>
                            </div>

                            <div class="footer-description">
                                <ul>
                                    <li><i class="fa fa-truck"></i>تحویل پستی سریع</li>
                                    <li><i class="fa fa-plane"></i>ارسال با پست پیشتاز و سفارشی</li>
                                    <li><i class="fa fa-cart-arrow-down"></i>خرید آسان و راحت</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="news-form">
                                <h5>مجوزهای فروشگاه</h5>
                            </div>
                            <div class="footer-description2">
                                <ul>

                                    <li>
                                        <a referrerpolicy="origin" target="_blank" href="https://trustseal.enamad.ir/?id=250376&amp;Code=BqY6LKdVVREpNlrKLQLG"><img referrerpolicy="origin" src="https://Trustseal.eNamad.ir/logo.aspx?id=250376&amp;Code=BqY6LKdVVREpNlrKLQLG" alt="" style="cursor:pointer" id="BqY6LKdVVREpNlrKLQLG"></a> |
                                        <script src="https://www.zarinpal.com/webservice/TrustCode" type="text/javascript"></script>

                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="news-form">
                                <h5>آدرس و شماره</h5>
                                <div class="footer-description2">
                                    <ul>
                                        <li><a class="badge-info" href="tel:@info.Phone"> @info.Phone </a></li>
                                        <li>@info.Address</li>
                                        <li>کدپستی : @info.Zipcode</li>
                                        @if (info.Instagram != string.Empty)
                                        {
                                            <li><a class="badge-info" href="@info.Instagram"> اینستاگرام </a></li>
                                        }

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    </div>

}

Ui/Views/Shared/_SliderHome.cshtml
@model IEnumerable<Entities.Product>

@if (Model != null && Model.Count()>0)
{

    <div class="container div-cast">
        <div class="row">
            <div class="col-md-12">
                <div class="slider-box">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            @for (int i = 0; i < Model.Count(); i++)
                            {
                                if (i == 0)
                                {
                                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                }
                                else
                                {
                                    <li data-target="#carouselExampleIndicators" data-slide-to="@i"></li>
                                }

                            }

                        </ol>

                        <div class="carousel-inner">
                            @for (int i = 0; i < Model.Count(); i++)
                            {

                                if (i == 0)
                                {
                                    <div class="carousel-item active">
                                        <div class="col-md-6" style="padding-top: 20px;">
                                            <h4>@Model.ToList()[i].Name</h4>
                                            @*<span>پرتابل خورشیدی</span>*@
                                            <p>@Model.ToList()[i].Description</p>
                                            <a asp-route-id="@Model.ToList()[i].Id" asp-action="ShowDetails" asp-controller="Product" asp-area=""
                                               class="btn-dark btn-sm">لینک محصول پر بازدید</a>
                                        </div>
                                        <div class="col-md-6">
                                            <img src="~/img/Product/normalimage/@Model.ToList()[i].ImageName" class="w-75">
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <div class="col-md-6" style="padding-top: 20px;">
                                            <h4>@Model.ToList()[i].Name</h4>
                                            <p>@Model.ToList()[i].Description</p>
                                            <a asp-route-id="@Model.ToList()[i].Id" asp-action="ShowDetails" asp-controller="Product" asp-area=""
                                               class="btn-dark btn-sm">لینک محصول پر بازدید</a>
                                        </div>
                                        <div class="col-md-6">
                                            <img src="~/img/Product/normalimage/@Model.ToList()[i].ImageName" class="w-75">
                                        </div>
                                    </div>

                                }
                            }
                        </div>

                    </div>
                </div>
                <!--slider-box-->
            </div>
        </div>
    </div>

}

Ui/Views/Shared/_adminpanel.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> _signInManager
@inject UserManager<AppUser> _userManager

<div class="col-md-3">

    <div class="div-cart text-center">
        <a asp-action="Index" asp-controller="Home" asp-area="">
            <img src="~/img/Brand.png" class="img-fluid" style="height:64px;" />
        </a>
    </div>
    <form asp-area="admin" asp-controller="AdminProfile" asp-action="Logout"
          method="post" class="text-center mb-3">
        <div class="">
            <hr class="break" />
            <button type="submit" class="btn btn-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
                    <path d="M7.5 1v7h1V1h-1z" />
                    <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z" />
                </svg>
            </button>

            <a asp-action="Index" asp-controller="Home" asp-area="" class="btn btn-info">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
                    <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z" />
                </svg>
            </a>

        </div>
    </form>



    <div class=" div-cart menu">

        <div class="div-cart-header">
            <h4>
                <a asp-controller="AdminProfile" asp-area="admin" asp-action="Index">داشبورد مدیریت</a>

            </h4>
        </div>
        <ul>

            <li class="main-li first-li">
                <a href="#">خرید انجام شده</a>
                <ul>
                    <li><a asp-controller="Order" asp-area="admin" asp-action="Index">سفارشات</a></li>
                </ul>
            </li>

            <li class="main-li first-li">
                <a href="#">محصولات</a>
                <ul>
                    <li><a asp-controller="Category" asp-area="admin" asp-action="Index">گروه بندی </a></li>
                    <li><a asp-controller="Product" asp-area="admin" asp-action="Index">محصولات</a></li>
                </ul>
            </li>


            <li class="main-li">
                <a href="#">کاربران</a>
                <ul>
                    <li><a asp-controller="Account" asp-area="admin" asp-action="Index">کاربران</a></li>
                    @*<li><a asp-controller="Account" asp-area="admin" asp-action="RoleIndex">نقش</a></li>*@
                </ul>
            </li>

            <li class="main-li">
                <a href="#">مقالات</a>
                <ul>
                    <li><a asp-controller="Article" asp-area="admin" asp-action="Index">مقالات</a></li>
                    <li><a asp-controller="Article" asp-area="admin" asp-action="Create">نوشتن مقاله</a></li>
                </ul>
            </li>

            <li class="main-li">
                <a href="#">نظرات</a>
                <ul>
                    <li><a asp-controller="Comment" asp-area="admin" asp-action="Index">نظرات جدید</a></li>
                    <li><a asp-controller="Comment" asp-area="admin" asp-action="GetAll">همه نظرات</a></li>
                </ul>
            </li>



        </ul>
    </div>

    @section script{

    }

</div>

Ui/Views/Shared/_userpanel.cshtml
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-brand dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                پروفایل
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" asp-action="ChangePassword" asp-controller="UserProfile" asp-area="user">تغییر رمز </a>
                <form class="dropdown-item" asp-action="Logout" asp-controller="Account" asp-area="" method="post">
                    <input type="submit" class="btn btn-light btn-block" value="خروج" />
                </form>
            </div>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-area="">صفحه اصلی فروشگاه <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="UserProfile" asp-area="user">مشخصات </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="User" asp-controller="Order" asp-action="ShowOrderPaid">پیگیری خرید </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-area="User" asp-controller="Order" asp-action="Index">سوابق خرید </a>
                </li>

            </ul>

        </div>
    </nav>
</div>