Ui/Areas/user/Models/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Ui.Areas.user.Models
{
    public class ChangePasswordViewModel
    {
        [Display(Name = "رمز جدید")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "این فیلد نباید خالی باشد")]
        [MinLength(8, ErrorMessage = "حداقل 8 حرف ضروری است"), MaxLength(24, ErrorMessage = "حداکثر 24 حرف میتوانید وارد نمایید.")]
        public string Password { get; set; }

        [Display(Name = "تکرار رمز جدید")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "این فیلد نباید خالی باشد")]
        [MinLength(8, ErrorMessage = "حداقل 8 حرف ضروری است"), MaxLength(24, ErrorMessage = "حداکثر 24 حرف میتوانید وارد نمایید.")]
        [Compare("Password", ErrorMessage = "رمز جدید با تکرار رمز یکسان نیست.")]
        public string ConfirmPassword { get; set; }
    }
}

Ui/Areas/user/Models/ConfirmPhoneNumberViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Ui.Areas.user.Models
{
    public class ConfirmPhoneNumberViewModel
    {
        [Display(Name = "تاییدیه موبایل")]
        public bool PhoneNumberConfirmed { get; set; }
        [Display(Name = "شماره تماس")]
        public string PhoneNumber { get; set; }
        [Display(Name = "کد اعتبار سنجی")]
        public string CodeOtp { get; set; }
    }
}

Ui/Areas/user/Controllers/UserProfileController.cs
using DAL.Servieces;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Ui.Areas.user.Models;
using Ui.Tools;

namespace Ui.Areas.user.Controllers
{
    [Area("user")]
    [Authorize(Roles = "user")]
    public class UserProfileController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IUserService _userService;
        private static string _codeOTP;
        public UserProfileController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IUserService userService)
        {
            _codeOTP = string.Empty;
            _signInManager = signInManager;
            _userManager = userManager;
            _userService = userService;
        }

        public IActionResult Index()
        {
            string usreId = _userManager.GetUserId(User);
            AppUser model = _userService.GetById(usreId);
            return View(model);
        }

        #region Edit
        [HttpGet]
        public IActionResult Edit()
        {
            string usreId = _userManager.GetUserId(User);
            AppUser model = _userService.GetById(usreId);
            return View(model);

            //UserInfoViewModel model = new UserInfoViewModel();
            //var userName = _userManager.GetUserName(User);
            //var user = _dbcontex.Users.Where(u => u.UserName == userName).FirstOrDefault();
            //if (user == null)
            //{
            //    return View("NotFound");
            //}
            //model.FirstName = user.FirstName;
            //model.LastName = user.LastName;
            //model.PhoneNumber = user.PhoneNumber;
            //model.PhoneNumberConfirmed = user.PhoneNumberConfirmed;
            //model.Address = user.Address;
            //model.PostCode = user.PostCode;
            //return View(model);
        }


        [HttpPost]
        public IActionResult Edit(AppUser user)
        {
            _userService.Update(user);
            string userId = _userManager.GetUserId(User);
            AppUser model = _userService.GetById(userId);
            return View("Index", model);

            //UserInfoViewModel model = new UserInfoViewModel();
            //var userName = _userManager.GetUserName(User);
            //var user = _dbcontex.Users.Where(u => u.UserName == userName).FirstOrDefault();
            //if (user == null)
            //{
            //    return View("NotFound");
            //}
            //// update data
            //user.FirstName = FormData.FirstName;
            //user.LastName = FormData.LastName;
            //user.Address = FormData.Address;
            //user.PostCode = FormData.PostCode;
            //_dbcontex.Users.Update(user);
            //_dbcontex.SaveChanges();
            ////------------------- return
            //model.FirstName = user.FirstName;
            //model.LastName = user.LastName;
            //model.PhoneNumber = user.PhoneNumber;
            //model.PhoneNumberConfirmed = user.PhoneNumberConfirmed;
            //model.Address = user.Address;
            //model.PostCode = user.PostCode;
        }
        #endregion

        #region Change-password
        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        /// <summary>
        /// change password without old password
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel password)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.error = true;
                return View(password);
            }

            string userId = _userManager.GetUserId(User);
            AppUser user = _userService.GetById(userId);
            if (user != null)
            {
                ViewBag.FullName = user.FirstName + " " + user.LastName;
                // Generate Token
                var token = await _userManager.GeneratePasswordResetTokenAsync(user);
                // Set new Password
                var result = await _userManager.ResetPasswordAsync(user, token, password.Password);
                if (result.Succeeded)
                {
                    ViewBag.Result = true;
                }
                else
                {
                    ViewBag.Result = false;
                }
                return View();
            }
            return View("NotFound");

            //// get user info
            //var userName = _userManager.GetUserName(User);
            //var user = _dbcontex.Users.Where(u => u.UserName == userName).FirstOrDefault();

            //UserInfoViewModel model = new UserInfoViewModel();
            //if (user == null)
            //{
            //    return View("NotFound");
            //}
            //ViewBag.FullName = user.FirstName + " " + user.LastName;
            //// change password with out old password
            ////Generate Token
            //var token = await _userManager.GeneratePasswordResetTokenAsync(user);
            ////Set new Password
            //var result = await _userManager.ResetPasswordAsync(user, token, DataForm.Password);
            //if (result.Succeeded)
            //{
            //    ViewBag.Result = true;
            //}
            //else
            //{
            //    ViewBag.Result = false;
            //}
            //return View();
        }
        #endregion

        #region Confirm-mobile
        [HttpGet]
        public IActionResult ConfirmPhoneNumber()
        {
            ConfirmPhoneNumberViewModel model = new ConfirmPhoneNumberViewModel();
            string userId = _userManager.GetUserId(User);
            AppUser user = _userService.GetById(userId);
            if (user != null)
            {
                model.PhoneNumber = user.PhoneNumber;
                model.PhoneNumberConfirmed = user.PhoneNumberConfirmed;
                return View(model);
            }
            else
            {
                return View("NotFound");
            }

            // var userName = _userManager.GetUserName(User);
            // var user = _dbcontex.Users.Where(u => u.UserName == userName).FirstOrDefault();
            //if (user == null)
            //{
            //    return View("NotFound");
            //}

            //model.PhoneNumber = user.PhoneNumber;
            //model.PhoneNumberConfirmed = user.PhoneNumberConfirmed;

            //return View(model);

        }

        [HttpPost]
        public IActionResult ConfirmPhoneNumber(ConfirmPhoneNumberViewModel input)
        {

            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //---------------complate it---------------
            //UserInfoViewModel model = new UserInfoViewModel();
            //var userName = _userManager.GetUserName(User);
            //var user = _dbcontex.Users.Where(u => u.UserName == userName).FirstOrDefault();
            string userId = _userManager.GetUserId(User);
            AppUser user = _userService.GetById(userId);
            if (user != null)
            {
                if (input.CodeOtp == _codeOTP)
                {
                    user.PhoneNumberConfirmed = true;
                    _userService.Update(user);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(input);
                }
            }
            else
            {
                return View("NotFound");
            }

            //_dbcontex.Users.Update(user);
            //_dbcontex.SaveChanges();

            //model.FirstName = user.FirstName;
            //model.LastName = user.LastName;
            //model.PhoneNumber = user.PhoneNumber;
            //model.PhoneNumberConfirmed = user.PhoneNumberConfirmed;
            //model.Address = user.Address;
            //model.PostCode = user.PostCode;
            //return View("Index", model);
            //return View();
        }

        /// <summary>
        /// درخواست کد احراز هویت
        /// </summary>
        public async Task<IActionResult> PostRegisterOTP(string PhoneNumber)
        {

            MessageSms message = new MessageSms();
            try
            {
                string userId = _userManager.GetUserId(User);
                AppUser user = _userService.GetById(userId);

                // string username = _userManager.GetUserName(User);
                // var user = _dbcontex.Users.Where(u => u.UserName == username).SingleOrDefault();
                _codeOTP = await message.SendOTP(user.PhoneNumber);
                return Json(new { message = "that greate code" });
            }
            catch { return Json(new { error = "Never Give Up" }); }



            //CompanyInfo info = new CompanyInfo();
            //string UserName = info.UserName;
            //string Password = info.Password;
            //int PatternCodeID = info.PatternCodeIDOTP;
            //DateTime SendDateTime = DateTime.Now;

            // خوندن اطلاعات به صورت تنظیماتی
            //XmlDocument doc = new XmlDocument();
            //doc.Load("DataXMLFile.xml");
            //string UserName = doc.SelectNodes("DocumentElement/Amoot")[0].SelectNodes("UserName")[0].InnerText;
            //string Password = doc.SelectNodes("DocumentElement/Amoot")[0].SelectNodes("Password")[0].InnerText;

Ui/Areas/user/Views/UserProfile/ChangePassword.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "تغییر رمز";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Ui.Areas.user.Models.ChangePasswordViewModel

<partial name="_userpanel" />

@if (@ViewBag.Result == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@ViewBag.FullName</strong> عزیز، رمز عبور شما با موفقیت بروزرسانی شد.
        <a asp-action="Index" asp-controller="UserPRofile" asp-area="user">بازگشت</a>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
else if (ViewBag.Result == false)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>@ViewBag.FullName</strong> عزیز، تغییر رمز عبور با خطا مواجه شد.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (ViewBag.error == true)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        در بروزرسانی رمز با خطا مواجه شدید.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}


<div class="card bg-light mb-3">
    <div class="card-header">تغییر رمز</div>
    <div class="card-body">
        @*form for edit*@
        <div class="row">
            <div class="col-12">

                <form asp-action="ChangePassword" asp-area="user" asp-controller="UserProfile" method="post" enctype="multipart/form-data">
                    <div class="form-group col-12">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" required class="form-control" maxlength="24" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="ConfirmPassword" class="control-label"></label>
                        <input asp-for="ConfirmPassword" required class="form-control" maxlength="24" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>

                    <button class="btn btn-success btn-sm" type="submit">بروزرسانی رمز</button> |
                    <a asp-action="Index" asp-controller="UserProfile" asp-area="user">بازگشت</a>
                </form>

            </div>
        </div>
        <hr />
        <div class="card-footer">
            <p>
                حداقل 8 حرف لازم است.
            </p>
        </div>

    </div>
</div>

Ui/Areas/user/Views/UserProfile/ConfirmPhoneNumber.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "تاییدیه شماره تماس";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Ui.Areas.user.Models.ConfirmPhoneNumberViewModel

<partial name="_userpanel" />

@*confirmed phone number*@
@if (Model.PhoneNumberConfirmed == true)
{
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-header">
                        تاییدبه شماره تماس
                    </div>
                    <div class="card-body">
                        <p>
                            شماره تماس
                            <strong>
                                @Model.PhoneNumber
                            </strong>
                            تایید شده است.
                        </p>
                        <br />

                        <a class="btn btn-primary" asp-action="Index" asp-controller="UserProfile" asp-area="user">
                            بازگشت به مشخصات
                        </a>
                        |
                        <a class="" asp-action="Index" asp-controller="Home" asp-area="">
                            صفحه اصلی فروشگاه
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
            </div>
        </div>
    </div>
}
@*need to confirm mobile*@
else
{
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-header">
                        تاییدیه شماره تماس
                    </div>
                    <div class="card-body">
                        <form asp-action="ConfirmPhoneNumber" asp-controller="UserProfile" asp-area="user" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="PhoneNumber" />
                            <p>
                                شماره تماس
                                <strong>
                                    @Model.PhoneNumber
                                </strong>
                                هنوز تایید نشده، ابتدا درخواست کد را بدهید، سپس منتظر بمانید تا کد به شماره شما ارسال شده و آن را در کادر زیر وارد نمایید و دکمه ارسال را کلیک نمایید.

                            </p>
                            <br />
                            <div class="form-group">
                                <lable class="col-12" for="PhoneNumber">کد را اینجا وارد نمایید.</lable>
                                <input asp-for="CodeOtp" placeholder="------"
                                       class="form-control col-12" />
                            </div>
                            <div class="form-group mt-2">

                                <a class="btn btn-sm btn-outline-dark" id="GetOTP">
                                    درخواست کد اعتبار سنجی
                                </a>
                                |
                                <input type="submit" class=" btn btn-success btn-sm col-2" value="ثبت کد" />
                            </div>
                        </form>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
            </div>
        </div>
    </div>
}

Ui/Areas/user/Views/UserProfile/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "ویرایش مسخصات";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Entities.AppUser

<partial name="_userpanel" />

<div class="card bg-light mb-3">
    <div class="card-header">ویرایش مشخصات کاربر</div>
    <div class="card-body">
        @*form for edit*@
        <div class="row">
            <div class="col-12">

                <form asp-action="Edit" asp-area="user" asp-controller="UserProfile" method="post" enctype="multipart/form-data">
                    <div class="form-group col-12">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" required class="form-control" value="@Model.FirstName" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" required class="form-control" value="@Model.LastName" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="Address" class="control-label"></label>
                        <textarea maxlength="450" required asp-for="Address"
                                  class="form-control" rows="2"
                                  placeholder="استان، شهر، محله، خیابان، فرعی، کوچه، طبقه،کوچه، پلاک، طبقه، واحد"></textarea>
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="Zipcode" class="control-label"></label>
                        <input asp-for="Zipcode" required class="form-control" value="@Model.Zipcode" />
                        <span asp-validation-for="Zipcode" class="text-danger"></span>
                    </div>
                    <button class="btn btn-success btn-sm" type="submit">بروزرسانی  مشخصات</button> |
                    <a asp-action="Index" asp-controller="UserProfile" asp-area="user">بازگشت</a>
                </form>

            </div>
        </div>

    </div>
</div>

Ui/Areas/user/Views/UserProfile/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    ViewData["Title"] = "پنل کاربری";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Entities.AppUser

<partial name="_userpanel" />

@*--------------Alert user for complate information--------------- *@
@if (Model.PhoneNumberConfirmed == false || Model.Address == null || Model.Zipcode == null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">تکمیل مشخصات</h4>
        @*title of message*@
        <p>
            <strong>
                @Model.FirstName @Model.LastName
            </strong>
            عزیز، برای دریافت خدمات از فروشگاه، مشخصات خود را کامل نمایید.
        </p>
        <hr>
        <p class="mb-0">
            @*check phone number*@
            @if (Model.PhoneNumberConfirmed == false)
            {
                <span>
                    شماره تماس
                    <strong>
                        @Model.PhoneNumber
                    </strong>
                    هنوز تایید نشده
                </span>
            }
            @*check address*@
            @if (Model.Address == null)
            {
                <br />
                <span>
                    هنوز آدرسی ثبت نشده
                </span>
            }
            @*check post code*@
            @if (Model.Zipcode == null)
            {
                <br />
                <span>
                    هنوز کد پستی ثبت نشده
                </span>
            }

        </p>
        <hr>
        @*button confirm phone number*@
        @if (Model.PhoneNumberConfirmed == false)
        {
            <a asp-action="ConfirmPhoneNumber" asp-controller="UserProfile" asp-area="user">تایید شماره موبایل</a>
        }
        @*button complate information*@
        @if (Model.Address == null || Model.Zipcode == null)
        {
            <a class="btn btn-outline-info" asp-action="Edit" asp-controller="UserProfile" asp-area="user">تکمیل مشخصات</a>
        }
    </div>

}



<div class="">
    <div class="card bg-light mb-3">
        <div class="card-header">مشخصات </div>
        <div class="card-body">
            <h5 class="card-title">@Model.FirstName @Model.LastName</h5>
            <p class="card-text">
                @*Adress*@
                <span>
                    آدرس:
                </span>
                @if (@Model.Address != null)
                {
                    <strong>
                        @Model.Address
                    </strong>

                }
                else
                {
                    <strong>
                        هنوز آدرسی ثبت نشده
                    </strong>
                }

                <br />
                @*Post Code*@
                <span>
                    کد پستی:
                </span>
                @if (@Model.Zipcode != null)
                {
                    <strong>
                        @Model.Zipcode
                    </strong>
                }
                else
                {
                    <strong>
                        هنوز کد پستی ثبت نشده
                    </strong>
                }

                <br />
                <hr />
                @*phone number*@
                <span>شماره تماس: </span><strong>@Model.PhoneNumber</strong>
                @if (Model.PhoneNumberConfirmed)
                {
                    <span class="text-success">تایید شده</span>
                }
                else
                {
                    <span class="text-danger">تایید نشده</span>
                    <br />
                    <a asp-action="ConfirmPhoneNumber" asp-controller="UserProfile" asp-area="user">دریافت کد تاییدیه موبایل</a>
                }
            </p>
            <hr />
            <a class="btn btn-outline-info" asp-action="Edit" asp-controller="UserProfile" asp-area="user">ویرایش مشخصات</a>
        </div>
    </div>
</div>

Ui/Areas/user/Views/UserProfile/NotFound.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@{
    ViewData["Title"] = "صفحه مورد نظر یافت نشد";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="top2">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="login">
                    <a asp-action="Index" asp-controller="Home" asp-area="" class="mybtn"><i class="fas fa-home"></i>صفحه اصلی</a>
                </div>
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
</div>

<br />

<div class="flex-center position-ref full-height bg-white">
    <div class="code">
        404
    </div>

    <div class="message" style="padding: 10px;">
        صفحه مورد نظر یافت نشد!
    </div>
</div>